# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/fan/Desktop/summer_school/wave/wave.cache/wt [current_project]
set_property parent.project_path C:/Users/fan/Desktop/summer_school/wave/wave.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/fan/Desktop/summer_school/wave/ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/fan/Desktop/summer_school/wave/wave.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/fan/Desktop/summer_school/wave/matlab/Square_Wave_Rom.coe
add_files C:/Users/fan/Desktop/summer_school/wave/matlab/Triangle_Wave_Rom.coe
add_files C:/Users/fan/Desktop/summer_school/wave/matlab/Sin_Wave_Rom.coe
add_files C:/Users/fan/Desktop/summer_school/wave/matlab/sawtooth_Wave_Rom.coe
read_verilog -library xil_defaultlib {
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/ad_sample.v
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/video_define.v
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/color_bar.v
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/grid_display.v
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/smg.v
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/timing_gen_xy.v
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/uart_rx.v
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/uart_tx.v
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/wav_display.v
  C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/new/DDS.v
}
read_ip -quiet c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Square/Square.xci
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Square/Square_ooc.xdc]

read_ip -quiet C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Triangle/Triangle.xci
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Triangle/Triangle_ooc.xdc]

read_ip -quiet C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Sin/Sin.xci
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Sin/Sin_ooc.xdc]

read_ip -quiet C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/sawtooth/sawtooth.xci
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/sawtooth/sawtooth_ooc.xdc]

read_ip -quiet C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/video_pll/video_pll.xci
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/video_pll/video_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/video_pll/video_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc]

read_ip -quiet C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/dpram2048x8/dpram2048x8.xci
set_property used_in_implementation false [get_files -all c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/dpram2048x8/dpram2048x8_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/fan/Desktop/summer_school/wave/wave.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files C:/Users/fan/Desktop/summer_school/wave/wave.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top DDS -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DDS.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DDS_utilization_synth.rpt -pb DDS_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
