# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Triangle/Triangle.xci
# IP: The module: 'Triangle' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Triangle/Triangle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Triangle'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Triangle/Triangle.xci
# IP: The module: 'Triangle' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fan/Desktop/summer_school/wave/wave.srcs/sources_1/ip/Triangle/Triangle_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Triangle'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
